# Generated by Django 4.2.30 on 2026-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineaccesscode',
            name='duration_months',
            field=models.IntegerField(default=6),
        ),
    ]
