# Generated by Django 4.2.30 on 2026-06-24 19:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_magazineaccesscode_duration_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.TimeField(default=datetime.time(8, 0))),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.AlterModelOptions(
            name='inappnotification',
            options={'ordering': ['-scheduled_for', '-created_at']},
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='scheduled_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
